plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.107'
    id 'io.freefair.lombok' version '8.7.1'
    id 'org.ajoberstar.grgit' version'5.3.3'
}

apply from: "$rootDir/gradle/scripts/version.gradle"
group = mod_group_id


base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

apply from: "$rootDir/gradle/scripts/repositories.gradle"
apply from: "$rootDir/gradle/scripts/modDevGradle.gradle"
apply from: "$rootDir/gradle/scripts/resources.gradle"
apply from: "$rootDir/dependencies.gradle"

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

lombok {
    version = "1.18.34"
}
